"""
Stub module for shipha.prompts.base.

Auto-generated by shipha.tools.stub_generator.
Pending port from ShinkaEvolve.
"""


# TODO: Port from ShinkaEvolve
BASE_SYSTEM_MSG: str = ""
"""Placeholder constant. Pending port from ShinkaEvolve."""
