"""
Stub module for shipha.prompts.diff.

Auto-generated by shipha.tools.stub_generator.
Pending port from ShinkaEvolve.
"""


# TODO: Port from ShinkaEvolve
DIFF_SYS_FORMAT: str = ""
"""Placeholder constant. Pending port from ShinkaEvolve."""

# TODO: Port from ShinkaEvolve
DIFF_ITER_MSG: str = ""
"""Placeholder constant. Pending port from ShinkaEvolve."""
