"""
Stub module for shipha.database.sqlite_db.

Auto-generated by shipha.tools.stub_generator.
Pending port from ShinkaEvolve.
"""

from dataclasses import dataclass
from typing import Any, Optional


@dataclass
class DatabaseConfig:
    """
    Configuration for database config.

    Pending port from ShinkaEvolve.
    """

    pass


class ProgramDatabase:
    """
    program database.

    Pending port from ShinkaEvolve.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Initialize ProgramDatabase."""
        raise NotImplementedError("Pending port from ShinkaEvolve")


class Program:
    """
    program.

    Pending port from ShinkaEvolve.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Initialize Program."""
        raise NotImplementedError("Pending port from ShinkaEvolve")
