"""
Stub module for shipha.launch.scheduler.

Auto-generated by shipha.tools.stub_generator.
Pending port from ShinkaEvolve.
"""

from dataclasses import dataclass
from typing import Any, Optional


@dataclass
class LocalJobConfig:
    """
    Configuration for local job config.

    Pending port from ShinkaEvolve.
    """

    pass


@dataclass
class SlurmJobConfig:
    """
    Configuration for slurm job config.

    Pending port from ShinkaEvolve.
    """

    pass


class JobScheduler:
    """
    job scheduler.

    Pending port from ShinkaEvolve.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Initialize JobScheduler."""
        raise NotImplementedError("Pending port from ShinkaEvolve")
